### ISSUE TITLE
Refactor AWS SSM to use new key

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#172]
Our current infra uses a hard coded AWS key into SSM. Refactor out the old key with the new one.

**Comment by dinterr** [comment]
I updated the credentials found in SSM Parameter Store. Please note that they are not a part of the CDK code and are created manually.  
In future, I can suggest using [GitHub OpenID Connect provider]( https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services ) for access to the repositories. It depends on the role-based access rather than the credentials of an individual user.

**Comment by michaelmarshall** [comment]
Ok copy that. Thanks Roks.
